# Generated by Django 2.2.6 on 2019-11-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='nick',
        ),
    ]
