# Generated by Django 2.2.6 on 2019-11-21 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_remove_perfiles_nick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='perfiles',
            new_name='Profile',
        ),
    ]
